import { Metadata } from "next";
import React from "react";
// import "@styles/globals.css";
import { IconSidebar } from "@components/icon-sidebar";
import { AppSidebar } from "@components/sidebar";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //   <body>
        <div className="flex h-screen w-full overflow-hidden">
          <IconSidebar />
          <div className="flex flex-1 overflow-hidden">
            <AppSidebar />
            <main className="flex-1 overflow-auto bg-white">{children}</main>
          </div>
        </div>
    //   </body>
    // </html>
  );
}
